### PR TITLE
feat: support layouts

### LINKED ISSUE #50: [feature request]  layout feature
Hi, great works on this!!

Providing layout feature just like nuxt.js would be very helpful.
I'm wondering if it is even possible to have such feature in vite.
Do you have any suggestion on how to do this?
Thanks!!

### PR DESCRIPTION
**Pull request by JohnCampionJr**
Sorry about that, I hit the wrong thing and screwed up my branch.  

Closes #50 

This is pre-plugin code for discussion.  Willing to work on integrating with `Vite-plugin-pages` if @hannoeru is interested.

If not, can refactor into Vite-plugin-layouts instead.

### CODE REVIEW

**Comment by JohnCampionJr** [comment]
FYI, I have started work on a separate vite plugin for this.  I think its different enough to separate from Vite-plugin-pages and this way different versions can iterate.  If they should be merged at some point, we can do that later.

**Comment by hannoeru** [comment]
I think is better to separate it to a different plugin.
In `src/layouts/_setup.ts` you can use [glob Import](https://vitejs.dev/guide/features.html#glob-import) to get layout components.

**Comment by JohnCampionJr** [comment]
Now using new plugin.  Probably some tweaks to be made there; open to suggestions.

**Comment by hannoeru** [comment]
Actually, what I means is you can build a component to swap layout and pass vite's glob import in to it's props.
Then we can add a `wrap component` option in `vite-plugin-page`.

**Comment by JohnCampionJr** [comment]
> Actually, what I means is you can build a component to swap layout and pass vite's glob import in to it's props.
> Then maybe we can add a `wrap component` option in `vite-plugin-page`.

I'm really confused now.  I thought you wanted it in a different plugin.  I've already built it as such.

Can you add any more details to what you're suggesting now?  Where would the component live? @antfu didn't want the infrastructure cluttering up Vitesse.

**Comment by hannoeru** [comment]
Sorry about that, I just thinking about using vite plugin or use vite's glob import with a layout component. Both works.

**Comment by JohnCampionJr** [comment]
> Sorry about that, I just thinking about using vite plugin or use vite's glob import with a layout component. Both works.

I used your great work as base to build the vite plugin with a virtual module.  It creates the imports the same way Vite's glob import does and feeds them to a layout component it creates and then that wraps around the routes (generated by your plugin).

**Comment by antfu** [comment]
Great, thanks!

**Pull request merged**
