### PR TITLE
feat: add vite-plugin-vue-i18n and some updates

### PR DESCRIPTION
**Pull request by kazupon**

### CODE REVIEW

**Comment by antfu** [comment]
That's cool! Thanks.

If we have the plugin, do we need the `message.ts` anymore?

I am not sure about changing `i18n` to `I18n` which AFAIK it's abbreviated as `i18n` in case of the misread with `I` and `1`. Refer to https://en.wikipedia.org/wiki/Internationalization_and_localization. Or did I missed anything?

**Comment by antfu** [comment]
We are using `pnpm` for this project, can you omit the yarn.lock? Thanks.

**Comment by kazupon** [comment]
> If we have the plugin, do we need the `messages.ts` anymore?

Yes!
We can get the available locales with using `avairableLocales`  property.
https://vue-i18n-next.intlify.dev/api/composition.html#availablelocales

So, In `Footer.vue`, You can refactor with it, and you can move `json` resources importing to `i18n.ts`.

> it's abbreviated as `i18n` in case of the misread with `I` and `1`. 

Oh, I've never heard of that before. 
in about Internationalization context, numeronyms is hard… 😅 

I've updated it to be more consistent in appearance, which is preferable.

Indeed, for readability, it seems better to keep `i`!
I will revert if you wish. :)

**Comment by antfu** [comment]
> messages.ts and availableLocales

Would you like to do that in this PR or I can do it later for sure.

> i18n vs I18n

Well, now I am not sure about it as I have seen both been used in several places. For example, https://www.w3.org/International/ is even mixing with both on the same page 😅. I'd say let's go with `I18n` to align with Vue I18n 👍

**Comment by kazupon** [comment]
> Would you like to do that in this PR or I can do it later for sure.

I've just updated!

> I'd say let's go with `I18n` to align with Vue I18n 👍

Okay, I get it!

**Pull request merged**
